# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "jquery_on_rails"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joe Khoobyar"]
  s.date = "2012-02-06"
  s.description = "A complete replacement for Rails 3 javascript helpers and unobstrusive javacript (ujs) using JQuery instead of prototype/scriptaculous"
  s.email = "joe@ankhcraft.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "jquery_on_rails.gemspec",
    "lib/jquery_on_rails.rb",
    "lib/jquery_on_rails/helpers/jquery_helper.rb",
    "lib/jquery_on_rails/helpers/jquery_ui_helper.rb",
    "lib/jquery_on_rails/railtie.rb",
    "public/javascripts/jquery-ui-effects.js",
    "public/javascripts/jquery.js",
    "public/javascripts/rails.js",
    "spec/dummy/app/controllers/dummy_controller.rb",
    "spec/dummy/app/helpers/dummy_helper.rb",
    "spec/dummy/config/application.rb",
    "spec/dummy/config/boot.rb",
    "spec/dummy/config/environment.rb",
    "spec/dummy/config/environments/test.rb",
    "spec/dummy/config/routes.rb",
    "spec/jquery_helper_spec.rb",
    "spec/jquery_on_rails_spec.rb",
    "spec/jquery_ui_helper_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/joekhoobyar/jquery_on_rails"
  s.require_paths = ["lib"]
  s.rubyforge_project = "jquery_on_rails"
  s.rubygems_version = "1.8.15"
  s.summary = "JQuery on Rails - Replace prototype/scriptaculous with jquery"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<actionpack>, ["~> 3.1.0"])
      s.add_runtime_dependency(%q<prototype-rails>, ["~> 3.1.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
    else
      s.add_dependency(%q<actionpack>, ["~> 3.1.0"])
      s.add_dependency(%q<prototype-rails>, ["~> 3.1.0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
    end
  else
    s.add_dependency(%q<actionpack>, ["~> 3.1.0"])
    s.add_dependency(%q<prototype-rails>, ["~> 3.1.0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
  end
end

